services:
  db:
    image: postgres:16-alpine
    container_name: lottery-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lottery_user -d lottery_db" ]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak-db:
    image: postgres:16-alpine
    container_name: lottery-keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_NAME}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: lottery-keycloak
    restart: unless-stopped
    depends_on:
      keycloak-db:
        condition: service_healthy
    command: [ "start-dev", "--import-realm", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false" ]
    environment:
      # bootstrap admin (from .env)
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}

      # postgres
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      # опційно (зручно для readiness/health у dev)
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      # сюди потім покладемо realm-export.json
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak-themes/lottery-theme:/opt/keycloak/themes/lottery-theme

  mailhog:
    image: mailhog/mailhog:latest
    container_name: lottery-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build: .
    container_name: lottery-backend
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET}
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started

volumes:
  db_data:
  keycloak_db_data:
  pgadmin_data:
